language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4snapshot'

before_install: composer install

script: composer test:unit:coverage

after_success:
  - 'curl --silent https://codecov.io/bash | bash'
